<#assign className = "${tableDTO.className}">
    public static final String ${tableDTO.tableName?upper_case}_ADD_SUCCESS = "添加成功";
	public static final String ${tableDTO.tableName?upper_case}_ADD_FAIL = "添加失败";
	public static final String ${tableDTO.tableName?upper_case}_ADD_REPEAT = "";
	public static final String ${tableDTO.tableName?upper_case}_MOD_SUCCESS = "修改成功";
	public static final String ${tableDTO.tableName?upper_case}_MOD_FAIL = "修改失败";
	public static final String ${tableDTO.tableName?upper_case}_MOD_REPEAT = "";
	public static final String ${tableDTO.tableName?upper_case}_DEL_SUCCESS = "删除成功";
	public static final String ${tableDTO.tableName?upper_case}_DEL_FAIL = "删除失败";
	public static final String ${tableDTO.tableName?upper_case}_FIND_SUCCESS = "查询成功";
	public static final String ${tableDTO.tableName?upper_case}_FIND_FAIL = "查询失败";
	public static final String ${tableDTO.tableName?upper_case}_FIND_LIST_SUCCESS = "查询列表成功";
	public static final String ${tableDTO.tableName?upper_case}_FIND_LIST_FAIL = "查询列表失败";
	public static final String ${tableDTO.tableName?upper_case}_TOTAL_COUNT_SUCCESS = "查询总数成功";
	public static final String ${tableDTO.tableName?upper_case}_TOTAL_COUNT_FAIL = "查询总数失败";